- name: Add User
  ansible.builtin.user:
   name: roboshop

- name: removing app
  ansible.builtin.file:
    path: /app
    state: absent

- name: create App directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading the application content and extracting
  ansible.builtin.unarchive:
   src: https://roboshop-artifacts.s3.amazonaws.com/'{{component}}'.zip
   dest: /tmp/'{{component}}'.zip
   remote_src: yes



















