- name: my sql server setup
  hosts: all
  become: true
  tasks:
    - name: copying repo files
      ansible.builtin.copy:
        src: sqlrepo
        dest: /etc/yum.repos.d/mysql.repo

    - name: disable the mysql
      ansible.builtin.shell: yum module disable mysql -y

    - name: Install mysql server
      ansible.builtin.yum:
        name: mysql-community-server
        state: present

    - name: start mysql service
      ansible.builtin.systemd:
        name: mysqld
        state: started
        enabled: yes

    - name: set root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass Roboshop@1