- name: copying repo files
  ansible.builtin.copy:
    src: sqlrepo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: Loading schema
  ansible.builtin.shell: mysql -h mysql-dev.sreddy.online -uroot -pRoboShop@1 </app/schema/'{{component}}'.sql





